/*
 * DIO_CFG.h
 *
 *  Created on: Aug 18, 2026
 *      Author: Target
 */

#ifndef APP_INCLUDE_MCAL_DIO_DIO_CFG_H_
#define APP_INCLUDE_MCAL_DIO_DIO_CFG_H_

#define DIO_CNF_OUTPUT 1
#define DIO_CNF_INPUT 0

#define DIO_CNF_HIGH 1
#define DIO_CNF_LOW 0

#define DIO_CNF_PULLUP 1
#define DIO_CNF_FLOATING 0


//////////DIRECTION


#define PORTA_PIN0_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN1_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN2_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN3_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN4_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN5_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN6_DIRECTION DIO_CNF_OUTPUT
#define PORTA_PIN7_DIRECTION DIO_CNF_OUTPUT

#define PORTB_PIN0_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN1_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN2_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN3_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN4_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN5_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN6_DIRECTION DIO_CNF_OUTPUT
#define PORTB_PIN7_DIRECTION DIO_CNF_OUTPUT

#define PORTC_PIN0_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN1_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN2_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN3_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN4_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN5_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN6_DIRECTION DIO_CNF_OUTPUT
#define PORTC_PIN7_DIRECTION DIO_CNF_OUTPUT

#define PORTD_PIN0_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN1_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN2_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN3_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN4_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN5_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN6_DIRECTION DIO_CNF_OUTPUT
#define PORTD_PIN7_DIRECTION DIO_CNF_OUTPUT

///////////VALUE


#define PORTA_PIN0_VALUE DIO_CNF_LOW
#define PORTA_PIN1_VALUE DIO_CNF_LOW
#define PORTA_PIN2_VALUE DIO_CNF_LOW
#define PORTA_PIN3_VALUE DIO_CNF_LOW
#define PORTA_PIN4_VALUE DIO_CNF_LOW
#define PORTA_PIN5_VALUE DIO_CNF_LOW
#define PORTA_PIN6_VALUE DIO_CNF_LOW
#define PORTA_PIN7_VALUE DIO_CNF_LOW

#define PORTB_PIN0_VALUE DIO_CNF_LOW
#define PORTB_PIN1_VALUE DIO_CNF_LOW
#define PORTB_PIN2_VALUE DIO_CNF_LOW
#define PORTB_PIN3_VALUE DIO_CNF_LOW
#define PORTB_PIN4_VALUE DIO_CNF_LOW
#define PORTB_PIN5_VALUE DIO_CNF_LOW
#define PORTB_PIN6_VALUE DIO_CNF_LOW
#define PORTB_PIN7_VALUE DIO_CNF_LOW

#define PORTC_PIN0_VALUE DIO_CNF_LOW
#define PORTC_PIN1_VALUE DIO_CNF_LOW
#define PORTC_PIN2_VALUE DIO_CNF_LOW
#define PORTC_PIN3_VALUE DIO_CNF_LOW
#define PORTC_PIN4_VALUE DIO_CNF_LOW
#define PORTC_PIN5_VALUE DIO_CNF_LOW
#define PORTC_PIN6_VALUE DIO_CNF_LOW
#define PORTC_PIN7_VALUE DIO_CNF_LOW

#define PORTD_PIN0_VALUE DIO_CNF_LOW
#define PORTD_PIN1_VALUE DIO_CNF_LOW
#define PORTD_PIN2_VALUE DIO_CNF_LOW
#define PORTD_PIN3_VALUE DIO_CNF_LOW
#define PORTD_PIN4_VALUE DIO_CNF_LOW
#define PORTD_PIN5_VALUE DIO_CNF_LOW
#define PORTD_PIN6_VALUE DIO_CNF_LOW
#define PORTD_PIN7_VALUE DIO_CNF_LOW


///////////INPUT MODE

#define PORTA_PIN0_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN1_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN2_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN3_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN4_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN5_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN6_INPUT_MODE DIO_CNF_PULLUP
#define PORTA_PIN7_INPUT_MODE DIO_CNF_PULLUP


#define PORTB_PIN0_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN1_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN2_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN3_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN4_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN5_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN6_INPUT_MODE DIO_CNF_PULLUP
#define PORTB_PIN7_INPUT_MODE DIO_CNF_PULLUP

#define PORTC_PIN0_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN1_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN2_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN3_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN4_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN5_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN6_INPUT_MODE DIO_CNF_PULLUP
#define PORTC_PIN7_INPUT_MODE DIO_CNF_PULLUP

#define PORTD_PIN0_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN1_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN2_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN3_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN4_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN5_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN6_INPUT_MODE DIO_CNF_PULLUP
#define PORTD_PIN7_INPUT_MODE DIO_CNF_PULLUP

#endif /* APP_INCLUDE_MCAL_DIO_DIO_CFG_H_ */
